services:
  # Service 1: The Database (PostgreSQL + PostGIS)
  db:
    image: postgis/postgis:15-3.3
    container_name: crisis_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Maps port 5432 on server to 5432 inside container
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Database Viewer (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: crisis_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db

# Define the storage volume
volumes:
  postgres_data: